# Generated by Django 4.0.5 on 2022-12-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='description',
        ),
        migrations.AddField(
            model_name='about',
            name='CGPA',
            field=models.CharField(default=10, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='SchoolName',
            field=models.CharField(default=10, max_length=250),
            preserve_default=False,
        ),
    ]
