# Generated by Django 4.0.5 on 2022-12-26 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_about_description_about_cgpa_about_schoolname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
    ]
