# Generated by Django 4.0.5 on 2022-12-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='author_name',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='author_title',
            new_name='Designation',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_photo',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='testimonial',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='Tenure',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
